### ISSUE TITLE
Unable to fetch Twitch follows

### ISSUE THREAD

**Issue by Lonsfor** [vinszent/gnome-twitch#276]
Can't get streams from the followers tab and gives this error in terminal
`
[20:36:57] Warning - GNOME-Twitch : {GtTwitch:2192} Unable to fetch all followed channels with id '[id]' and oauth token '[token]' because: A followed stream did not exist as a followed channel`
`
[20:36:57] Warning - GNOME-Twitch : {GtFollowsManager:479} Unable to fetch Twitch follows because: Unable to fetch all followed channels with id '[id]' and oauth token '[token]' because: A followed stream did not exist as a followed channel
`

Using the Flatpak package.

**Comment by Haggus** [comment]
I've been having the same issue for a while now. Using gnome-twitch from AUR.

**Comment by vinszent** [comment]
Can I ask how many follows you guys have? 

Basically the error is saying that it's found a followed stream that doesn't exist as a followed channel which is weird. It could be a logic error in my code but the Twitch API can be pretty crap as well.

**Comment by Haggus** [comment]
I don't see any way to list all followed channels in twitch settings

**Comment by vinszent** [comment]
@Haggus Ok but would you say it's more than 100?

**Comment by Lonsfor** [comment]
I follow 162 channels.

**Comment by Lonsfor** [comment]
@Haggus followed channels are in twitch.tv/[name]/following

**Comment by Haggus** [comment]
@vinszent @Lonsfor In that case I've got 295 :)

**Comment by vinszent** [comment]
Got it, I think I've localised the problem to https://github.com/vinszent/gnome-twitch/blob/master/src/gt-twitch.c#L2173 where I do some special handling when you have more than 100 follows to be able to retrieve them all. I myself don't have more than 100 follows so that's why I haven't noticed this before but I'll get my test account to do further troubleshooting.

**Comment by vinszent** [comment]
Ok hopefully this should be fixed now or at the very least be less frequent. The Twitch API is a pain to work with so that's why this fix might not be 100%. I'm in the process of rewriting a lot of this, but this should keep it together until then 👍 .

**Comment by Haggus** [comment]
I can confirm the error is gone and I see my follows. However now it displays ALL follows, even the ones that are offline (unless that is what's supposed to happen). Thanks for fixing it 👍

**Comment by derpyderpaderp** [comment]
I was still receiving this error until I was only following 100 people. Not that big of a deal but still weird.

**Comment by drtwisted** [comment]
I experience this issue as well! 200+ followed channels.

**Comment by z3r0sTr3sS** [comment]
guys i have this issue and i don't understand how fix this issue .^.
